/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;

// ReSharper disable All

namespace MangosSharp.Data.Entities.RealmDatabase;

public sealed class Account
{
    public uint ActiveRealmId { get; set; }

    public string Email { get; set; }

    public byte Expansion { get; set; }

    public uint FailedLogins { get; set; }

    public uint Flags { get; set; }

    public byte Gmlevel { get; set; }

    /* Identifier */
    public uint Id { get; set; }

    public DateTimeOffset Joindate { get; set; }

    public string LastModule { get; set; }

    public string Locale { get; set; }

    public byte Locked { get; set; }

    public string LockedIp { get; set; }

    public uint ModuleDay { get; set; }

    public ulong Mutetime { get; set; }

    public string Os { get; set; }

    public string S { get; set; }

    public string Sessionkey { get; set; }

    public string Token { get; set; }

    public string Username { get; set; }

    public string V { get; set; }

}
public sealed class AccountBanned
{
    /* Account id */
    public int AccountId { get; set; }

    public byte Active { get; set; }

    public long BannedAt { get; set; }

    public string BannedBy { get; set; }

    public long ExpiresAt { get; set; }

    public int Id { get; set; }

    public string Reason { get; set; }

    public long UnbannedAt { get; set; }

    public string UnbannedBy { get; set; }

}
public sealed class AccountLogons
{
    public uint AccountId { get; set; }

    public int Id { get; set; }

    public string Ip { get; set; }

    public uint LoginSource { get; set; }

    public DateTimeOffset LoginTime { get; set; }

}
public sealed class AccountRaf
{
    public uint Referred { get; set; }

    public uint Referrer { get; set; }

}
public sealed class AntispamBlacklist
{
    public string String { get; set; }

}
public sealed class AntispamReplacement
{
    public string From { get; set; }

    public string To { get; set; }

}
public sealed class AntispamUnicodeReplacement
{
    public uint From { get; set; }

    public uint To { get; set; }

}
public sealed class IpBanned
{
    public long BannedAt { get; set; }

    public string BannedBy { get; set; }

    public long ExpiresAt { get; set; }

    public string Ip { get; set; }

    public string Reason { get; set; }

}
public sealed class Realmcharacters
{
    public ulong Acctid { get; set; }

    public byte Numchars { get; set; }

    public uint Realmid { get; set; }

}
public sealed class Realmlist
{
    public string Address { get; set; }

    public byte AllowedSecurityLevel { get; set; }

    public byte Icon { get; set; }

    public uint Id { get; set; }

    public string Name { get; set; }

    public float Population { get; set; }

    public int Port { get; set; }

    public string Realmbuilds { get; set; }

    /* Supported masks: 0x1 (invalid, not show in realm list), 0x2 (offline, set by mangosd), 0x4 (show version and build), 0x20 (new players), 0x40 (recommended) */
    public byte Realmflags { get; set; }

    public byte Timezone { get; set; }

}
public sealed class SystemFingerprintUsage
{
    public uint Account { get; set; }

    public uint? Activecpus { get; set; }

    public string Architecture { get; set; }

    public string Cputype { get; set; }

    public uint Fingerprint { get; set; }

    public uint Id { get; set; }

    public string Ip { get; set; }

    public uint? Pagesize { get; set; }

    public uint Realm { get; set; }

    public DateTime? Time { get; set; }

    public uint? Totalcpus { get; set; }

}
public sealed class UpTime
{
    public ushort Maxplayers { get; set; }

    public uint Realmid { get; set; }

    public string Startstring { get; set; }

    public ulong Starttime { get; set; }

    public ulong Uptime { get; set; }

}
