/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// ReSharper disable All

namespace MangosSharp.Data.Entities.RealmDatabase;

[Table("account")]
public sealed class Account
{
    [Column("active_realm_id", TypeName="int")]
    public uint ActiveRealmId { get; set; }

    [Column("email", TypeName="text")]
    [MaxLength(65535)]
    public string Email { get; set; }

    [Column("expansion", TypeName="tinyint")]
    public byte Expansion { get; set; }

    [Column("failed_logins", TypeName="int")]
    public uint FailedLogins { get; set; }

    [Column("flags", TypeName="int")]
    public uint Flags { get; set; }

    [Column("gmlevel", TypeName="tinyint")]
    public byte Gmlevel { get; set; }

    /* Identifier */
    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("joindate", TypeName="timestamp")]
    public DateTimeOffset Joindate { get; set; }

    [Column("last_module")]
    [MaxLength(32)]
    public string LastModule { get; set; }

    [Column("locale")]
    [MaxLength(4)]
    public string Locale { get; set; }

    [Column("locked", TypeName="tinyint")]
    public byte Locked { get; set; }

    [Column("lockedIp")]
    [MaxLength(30)]
    public string LockedIp { get; set; }

    [Column("module_day", TypeName="mediumint")]
    public uint ModuleDay { get; set; }

    [Column("mutetime", TypeName="bigint")]
    public ulong Mutetime { get; set; }

    [Column("os")]
    [MaxLength(4)]
    public string Os { get; set; }

    [Column("s", TypeName="longtext")]
    public string S { get; set; }

    [Column("sessionkey", TypeName="longtext")]
    public string Sessionkey { get; set; }

    [Column("token", TypeName="text")]
    [MaxLength(65535)]
    public string Token { get; set; }

    [Column("username")]
    [MaxLength(32)]
    public string Username { get; set; }

    [Column("v", TypeName="longtext")]
    public string V { get; set; }

}
[Table("account_banned")]
public sealed class AccountBanned
{
    /* Account id */
    [Column("account_id", TypeName="int")]
    public int AccountId { get; set; }

    [Column("active", TypeName="tinyint")]
    public byte Active { get; set; }

    [Column("banned_at", TypeName="bigint")]
    public long BannedAt { get; set; }

    [Column("banned_by")]
    [MaxLength(50)]
    public string BannedBy { get; set; }

    [Column("expires_at", TypeName="bigint")]
    public long ExpiresAt { get; set; }

    [Column("id", TypeName="int")]
    public int Id { get; set; }

    [Column("reason")]
    [MaxLength(255)]
    public string Reason { get; set; }

    [Column("unbanned_at", TypeName="bigint")]
    public long UnbannedAt { get; set; }

    [Column("unbanned_by")]
    [MaxLength(50)]
    public string UnbannedBy { get; set; }

}
[Table("account_logons")]
public sealed class AccountLogons
{
    [Column("accountId", TypeName="int")]
    public uint AccountId { get; set; }

    [Column("id", TypeName="int")]
    public int Id { get; set; }

    [Column("ip")]
    [MaxLength(30)]
    public string Ip { get; set; }

    [Column("loginSource", TypeName="int")]
    public uint LoginSource { get; set; }

    [Column("loginTime", TypeName="timestamp")]
    public DateTimeOffset LoginTime { get; set; }

}
[Table("account_raf")]
public sealed class AccountRaf
{
    [Column("referred", TypeName="int")]
    public uint Referred { get; set; }

    [Column("referrer", TypeName="int")]
    public uint Referrer { get; set; }

}
[Table("antispam_blacklist")]
public sealed class AntispamBlacklist
{
    [Column("string")]
    [MaxLength(64)]
    public string String { get; set; }

}
[Table("antispam_replacement")]
public sealed class AntispamReplacement
{
    [Column("from")]
    [MaxLength(32)]
    public string From { get; set; }

    [Column("to")]
    [MaxLength(32)]
    public string To { get; set; }

}
[Table("antispam_unicode_replacement")]
public sealed class AntispamUnicodeReplacement
{
    [Column("from", TypeName="mediumint")]
    public uint From { get; set; }

    [Column("to", TypeName="mediumint")]
    public uint To { get; set; }

}
[Table("ip_banned")]
public sealed class IpBanned
{
    [Column("banned_at", TypeName="bigint")]
    public long BannedAt { get; set; }

    [Column("banned_by")]
    [MaxLength(50)]
    public string BannedBy { get; set; }

    [Column("expires_at", TypeName="bigint")]
    public long ExpiresAt { get; set; }

    [Column("ip")]
    [MaxLength(32)]
    public string Ip { get; set; }

    [Column("reason")]
    [MaxLength(255)]
    public string Reason { get; set; }

}
[Table("realmcharacters")]
public sealed class Realmcharacters
{
    [Column("acctid", TypeName="bigint")]
    public ulong Acctid { get; set; }

    [Column("numchars", TypeName="tinyint")]
    public byte Numchars { get; set; }

    [Column("realmid", TypeName="int")]
    public uint Realmid { get; set; }

}
[Table("realmlist")]
public sealed class Realmlist
{
    [Column("address")]
    [MaxLength(32)]
    public string Address { get; set; }

    [Column("allowedSecurityLevel", TypeName="tinyint")]
    public byte AllowedSecurityLevel { get; set; }

    [Column("icon", TypeName="tinyint")]
    public byte Icon { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("name")]
    [MaxLength(32)]
    public string Name { get; set; }

    [Column("population", TypeName="float")]
    public float Population { get; set; }

    [Column("port", TypeName="int")]
    public int Port { get; set; }

    [Column("realmbuilds")]
    [MaxLength(64)]
    public string Realmbuilds { get; set; }

    /* Supported masks: 0x1 (invalid, not show in realm list), 0x2 (offline, set by mangosd), 0x4 (show version and build), 0x20 (new players), 0x40 (recommended) */
    [Column("realmflags", TypeName="tinyint")]
    public byte Realmflags { get; set; }

    [Column("timezone", TypeName="tinyint")]
    public byte Timezone { get; set; }

}
[Table("system_fingerprint_usage")]
public sealed class SystemFingerprintUsage
{
    [Column("account", TypeName="int")]
    public uint Account { get; set; }

    [Column("activecpus", TypeName="int")]
    public uint? Activecpus { get; set; }

    [Column("architecture")]
    [MaxLength(16)]
    public string Architecture { get; set; }

    [Column("cputype")]
    [MaxLength(64)]
    public string Cputype { get; set; }

    [Column("fingerprint", TypeName="int")]
    public uint Fingerprint { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("ip")]
    [MaxLength(16)]
    public string Ip { get; set; }

    [Column("pagesize", TypeName="int")]
    public uint? Pagesize { get; set; }

    [Column("realm", TypeName="int")]
    public uint Realm { get; set; }

    [Column("time", TypeName="datetime")]
    public DateTime? Time { get; set; }

    [Column("totalcpus", TypeName="int")]
    public uint? Totalcpus { get; set; }

}
[Table("uptime")]
public sealed class Uptime
{
    [Column("maxplayers", TypeName="smallint")]
    public ushort Maxplayers { get; set; }

    [Column("realmid", TypeName="int")]
    public uint Realmid { get; set; }

    [Column("startstring")]
    [MaxLength(64)]
    public string Startstring { get; set; }

    [Column("starttime", TypeName="bigint")]
    public ulong Starttime { get; set; }

    [Column("uptime", TypeName="bigint")]
    public ulong UpTime { get; set; }

}
