/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MangosSharp.Data.Entities.LogsDatabase;
using Microsoft.EntityFrameworkCore;

// ReSharper disable All

namespace MangosSharp.Data.Context;

public sealed class ClassiclogsDbContext : DbContext
{
    public ClassiclogsDbContext() {}
    public ClassiclogsDbContext(DbContextOptions options) : base(options) {}
    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<LogsAnticheat>().HasKey(e => new { e.Id });
        builder.Entity<LogsSpamdetect>().HasKey(e => new { e.Id });
        builder.Entity<LogsSpamdetect>().Property(e => e.Time).HasDefaultValue();
        builder.Entity<LogsSpamdetect>().Property(e => e.AccountId).HasDefaultValue();
        builder.Entity<LogsSpamdetect>().Property(e => e.FromGuid).HasDefaultValue();
        builder.Entity<LogsSpamdetect>().Property(e => e.Comment).HasDefaultValue();
    }

    public DbSet<LogsAnticheat> LogsAnticheats { get; set; }
    public DbSet<LogsSpamdetect> LogsSpamdetects { get; set; }
}
