/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// ReSharper disable All

namespace MangosSharp.Data.Entities.CharacterDatabase;

[Table("account_instances_entered")]
public sealed class AccountInstancesEntered
{
    /* Player account */
    [Column("AccountId", TypeName="int")]
    public uint AccountId { get; set; }

    /* Time when instance was entered */
    [Column("ExpireTime", TypeName="bigint")]
    public long ExpireTime { get; set; }

    /* ID of instance entered */
    [Column("InstanceId", TypeName="int")]
    public uint InstanceId { get; set; }

}
[Table("ahbot_items")]
public sealed class AhbotItems
{
    /* Chance item is added to AH upon bot visit, 0 for normal loot sources */
    [Column("add_chance", TypeName="int")]
    public uint AddChance { get; set; }

    /* Item Identifier */
    [Column("item", TypeName="int")]
    public uint Item { get; set; }

    /* Max amount added, not used when add_chance is 0 */
    [Column("max_amount", TypeName="int")]
    public uint MaxAmount { get; set; }

    /* Min amount added, not used when add_chance is 0 */
    [Column("min_amount", TypeName="int")]
    public uint MinAmount { get; set; }

    /* Item value, a value of 0 bans item from being sold/bought by AHBot */
    [Column("value", TypeName="int")]
    public uint Value { get; set; }

}
[Table("auction")]
public sealed class Auction
{
    [Column("buyguid", TypeName="int")]
    public uint Buyguid { get; set; }

    [Column("buyoutprice", TypeName="int")]
    public int Buyoutprice { get; set; }

    [Column("deposit", TypeName="int")]
    public int Deposit { get; set; }

    [Column("houseid", TypeName="int")]
    public uint Houseid { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("item_count", TypeName="int")]
    public uint ItemCount { get; set; }

    [Column("item_randompropertyid", TypeName="int")]
    public int ItemRandompropertyid { get; set; }

    /* Item Identifier */
    [Column("item_template", TypeName="int")]
    public uint ItemTemplate { get; set; }

    [Column("itemguid", TypeName="int")]
    public uint Itemguid { get; set; }

    [Column("itemowner", TypeName="int")]
    public uint Itemowner { get; set; }

    [Column("lastbid", TypeName="int")]
    public int Lastbid { get; set; }

    [Column("startbid", TypeName="int")]
    public int Startbid { get; set; }

    [Column("time", TypeName="bigint")]
    public ulong Time { get; set; }

}
[Table("bugreport")]
public sealed class Bugreport
{
    [Column("content", TypeName="longtext")]
    public string Content { get; set; }

    /* Identifier */
    [Column("id", TypeName="int")]
    public int Id { get; set; }

    [Column("type", TypeName="longtext")]
    public string Type { get; set; }

}
[Table("character_action")]
public sealed class CharacterAction
{
    [Column("action", TypeName="int")]
    public uint Action { get; set; }

    [Column("button", TypeName="tinyint")]
    public byte Button { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("type", TypeName="tinyint")]
    public byte Type { get; set; }

}
[Table("character_aura")]
public sealed class CharacterAura
{
    [Column("basepoints0", TypeName="int")]
    public int Basepoints0 { get; set; }

    [Column("basepoints1", TypeName="int")]
    public int Basepoints1 { get; set; }

    [Column("basepoints2", TypeName="int")]
    public int Basepoints2 { get; set; }

    /* Full Global Unique Identifier */
    [Column("caster_guid", TypeName="bigint")]
    public ulong CasterGuid { get; set; }

    [Column("effIndexMask", TypeName="int")]
    public uint EffIndexMask { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("item_guid", TypeName="int")]
    public uint ItemGuid { get; set; }

    [Column("maxduration", TypeName="int")]
    public int Maxduration { get; set; }

    [Column("periodictime0", TypeName="int")]
    public uint Periodictime0 { get; set; }

    [Column("periodictime1", TypeName="int")]
    public uint Periodictime1 { get; set; }

    [Column("periodictime2", TypeName="int")]
    public uint Periodictime2 { get; set; }

    [Column("remaincharges", TypeName="int")]
    public uint Remaincharges { get; set; }

    [Column("remaintime", TypeName="int")]
    public int Remaintime { get; set; }

    [Column("spell", TypeName="int")]
    public uint Spell { get; set; }

    [Column("stackcount", TypeName="int")]
    public uint Stackcount { get; set; }

}
[Table("character_battleground_data")]
public sealed class CharacterBattlegroundData
{
    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("instance_id", TypeName="int")]
    public uint InstanceId { get; set; }

    [Column("join_map", TypeName="int")]
    public int JoinMap { get; set; }

    [Column("join_o", TypeName="float")]
    public float JoinO { get; set; }

    [Column("join_x", TypeName="float")]
    public float JoinX { get; set; }

    [Column("join_y", TypeName="float")]
    public float JoinY { get; set; }

    [Column("join_z", TypeName="float")]
    public float JoinZ { get; set; }

    [Column("team", TypeName="int")]
    public uint Team { get; set; }

}
[Table("character_gifts")]
public sealed class CharacterGifts
{
    [Column("entry", TypeName="int")]
    public uint Entry { get; set; }

    [Column("flags", TypeName="int")]
    public uint Flags { get; set; }

    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("item_guid", TypeName="int")]
    public uint ItemGuid { get; set; }

}
[Table("character_homebind")]
public sealed class CharacterHomebind
{
    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Map Identifier */
    [Column("map", TypeName="int")]
    public uint Map { get; set; }

    [Column("position_x", TypeName="float")]
    public float PositionX { get; set; }

    [Column("position_y", TypeName="float")]
    public float PositionY { get; set; }

    [Column("position_z", TypeName="float")]
    public float PositionZ { get; set; }

    /* Zone Identifier */
    [Column("zone", TypeName="int")]
    public uint Zone { get; set; }

}
[Table("character_honor_cp")]
public sealed class CharacterHonorCp
{
    [Column("date", TypeName="int")]
    public uint Date { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("honor", TypeName="float")]
    public float Honor { get; set; }

    [Column("type", TypeName="tinyint")]
    public byte Type { get; set; }

    /* Creature / Player Identifier */
    [Column("victim", TypeName="int")]
    public uint Victim { get; set; }

    [Column("victim_type", TypeName="tinyint")]
    public byte VictimType { get; set; }

}
[Table("character_instance")]
public sealed class CharacterInstance
{
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("instance", TypeName="int")]
    public uint Instance { get; set; }

    [Column("permanent", TypeName="tinyint")]
    public byte Permanent { get; set; }

}
[Table("character_inventory")]
public sealed class CharacterInventory
{
    [Column("bag", TypeName="int")]
    public uint Bag { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Item Global Unique Identifier */
    [Column("item", TypeName="int")]
    public uint Item { get; set; }

    /* Item Identifier */
    [Column("item_template", TypeName="int")]
    public uint ItemTemplate { get; set; }

    [Column("slot", TypeName="tinyint")]
    public byte Slot { get; set; }

}
[Table("character_pet")]
public sealed class CharacterPet
{
    [Column("abdata", TypeName="longtext")]
    public string Abdata { get; set; }

    [Column("CreatedBySpell", TypeName="int")]
    public uint CreatedBySpell { get; set; }

    [Column("curhappiness", TypeName="int")]
    public uint Curhappiness { get; set; }

    [Column("curhealth", TypeName="int")]
    public uint Curhealth { get; set; }

    [Column("curmana", TypeName="int")]
    public uint Curmana { get; set; }

    [Column("entry", TypeName="int")]
    public uint Entry { get; set; }

    [Column("exp", TypeName="int")]
    public uint Exp { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("level", TypeName="int")]
    public uint Level { get; set; }

    [Column("loyalty", TypeName="int")]
    public uint Loyalty { get; set; }

    [Column("loyaltypoints", TypeName="int")]
    public int Loyaltypoints { get; set; }

    [Column("modelid", TypeName="int")]
    public uint Modelid { get; set; }

    [Column("name")]
    [MaxLength(100)]
    public string Name { get; set; }

    [Column("owner", TypeName="int")]
    public uint Owner { get; set; }

    [Column("PetType", TypeName="tinyint")]
    public byte PetType { get; set; }

    [Column("Reactstate", TypeName="tinyint")]
    public byte Reactstate { get; set; }

    [Column("renamed", TypeName="tinyint")]
    public byte Renamed { get; set; }

    [Column("resettalents_cost", TypeName="int")]
    public uint ResettalentsCost { get; set; }

    [Column("resettalents_time", TypeName="bigint")]
    public ulong ResettalentsTime { get; set; }

    [Column("savetime", TypeName="bigint")]
    public ulong Savetime { get; set; }

    [Column("slot", TypeName="int")]
    public uint Slot { get; set; }

    [Column("teachspelldata", TypeName="longtext")]
    public string Teachspelldata { get; set; }

    [Column("trainpoint", TypeName="int")]
    public int Trainpoint { get; set; }

    [Column("xpForNextLoyalty", TypeName="int")]
    public uint XpForNextLoyalty { get; set; }

}
[Table("character_queststatus")]
public sealed class CharacterQueststatus
{
    [Column("explored", TypeName="tinyint")]
    public byte Explored { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("itemcount1", TypeName="int")]
    public uint Itemcount1 { get; set; }

    [Column("itemcount2", TypeName="int")]
    public uint Itemcount2 { get; set; }

    [Column("itemcount3", TypeName="int")]
    public uint Itemcount3 { get; set; }

    [Column("itemcount4", TypeName="int")]
    public uint Itemcount4 { get; set; }

    [Column("mobcount1", TypeName="int")]
    public uint Mobcount1 { get; set; }

    [Column("mobcount2", TypeName="int")]
    public uint Mobcount2 { get; set; }

    [Column("mobcount3", TypeName="int")]
    public uint Mobcount3 { get; set; }

    [Column("mobcount4", TypeName="int")]
    public uint Mobcount4 { get; set; }

    /* Quest Identifier */
    [Column("quest", TypeName="int")]
    public uint Quest { get; set; }

    [Column("rewarded", TypeName="tinyint")]
    public byte Rewarded { get; set; }

    [Column("status", TypeName="int")]
    public uint Status { get; set; }

    [Column("timer", TypeName="bigint")]
    public ulong Timer { get; set; }

}
[Table("character_queststatus_weekly")]
public sealed class CharacterQueststatusWeekly
{
    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Quest Identifier */
    [Column("quest", TypeName="int")]
    public uint Quest { get; set; }

}
[Table("character_reputation")]
public sealed class CharacterReputation
{
    [Column("faction", TypeName="int")]
    public uint Faction { get; set; }

    [Column("flags", TypeName="int")]
    public int Flags { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("standing", TypeName="int")]
    public int Standing { get; set; }

}
[Table("character_skills")]
public sealed class CharacterSkills
{
    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("max", TypeName="mediumint")]
    public uint Max { get; set; }

    [Column("skill", TypeName="mediumint")]
    public uint Skill { get; set; }

    [Column("value", TypeName="mediumint")]
    public uint Value { get; set; }

}
[Table("character_social")]
public sealed class CharacterSocial
{
    /* Friend Flags */
    [Column("flags", TypeName="tinyint")]
    public byte Flags { get; set; }

    /* Friend Global Unique Identifier */
    [Column("friend", TypeName="int")]
    public uint Friend { get; set; }

    /* Character Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

}
[Table("character_spell")]
public sealed class CharacterSpell
{
    [Column("active", TypeName="tinyint")]
    public byte Active { get; set; }

    [Column("disabled", TypeName="tinyint")]
    public byte Disabled { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Spell Identifier */
    [Column("spell", TypeName="int")]
    public uint Spell { get; set; }

}
[Table("character_spell_cooldown")]
public sealed class CharacterSpellCooldown
{
    /* Spell category */
    [Column("Category", TypeName="int")]
    public uint Category { get; set; }

    /* Spell category cooldown expire time */
    [Column("CategoryExpireTime", TypeName="bigint")]
    public ulong CategoryExpireTime { get; set; }

    /* Global Unique Identifier, Low part */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Item Identifier */
    [Column("ItemId", TypeName="int")]
    public uint ItemId { get; set; }

    /* Spell cooldown expire time */
    [Column("SpellExpireTime", TypeName="bigint")]
    public ulong SpellExpireTime { get; set; }

    /* Spell Identifier */
    [Column("SpellId", TypeName="int")]
    public uint SpellId { get; set; }

}
[Table("character_stats")]
public sealed class CharacterStats
{
    [Column("agility", TypeName="int")]
    public uint Agility { get; set; }

    [Column("armor", TypeName="int")]
    public uint Armor { get; set; }

    [Column("attackPower", TypeName="int")]
    public uint AttackPower { get; set; }

    [Column("blockPct", TypeName="float")]
    public float BlockPct { get; set; }

    [Column("critPct", TypeName="float")]
    public float CritPct { get; set; }

    [Column("dodgePct", TypeName="float")]
    public float DodgePct { get; set; }

    /* Global Unique Identifier, Low part */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("intellect", TypeName="int")]
    public uint Intellect { get; set; }

    [Column("maxhealth", TypeName="int")]
    public uint Maxhealth { get; set; }

    [Column("maxpower1", TypeName="int")]
    public uint Maxpower1 { get; set; }

    [Column("maxpower2", TypeName="int")]
    public uint Maxpower2 { get; set; }

    [Column("maxpower3", TypeName="int")]
    public uint Maxpower3 { get; set; }

    [Column("maxpower4", TypeName="int")]
    public uint Maxpower4 { get; set; }

    [Column("maxpower5", TypeName="int")]
    public uint Maxpower5 { get; set; }

    [Column("maxpower6", TypeName="int")]
    public uint Maxpower6 { get; set; }

    [Column("maxpower7", TypeName="int")]
    public uint Maxpower7 { get; set; }

    [Column("parryPct", TypeName="float")]
    public float ParryPct { get; set; }

    [Column("rangedAttackPower", TypeName="int")]
    public uint RangedAttackPower { get; set; }

    [Column("rangedCritPct", TypeName="float")]
    public float RangedCritPct { get; set; }

    [Column("resArcane", TypeName="int")]
    public uint ResArcane { get; set; }

    [Column("resFire", TypeName="int")]
    public uint ResFire { get; set; }

    [Column("resFrost", TypeName="int")]
    public uint ResFrost { get; set; }

    [Column("resHoly", TypeName="int")]
    public uint ResHoly { get; set; }

    [Column("resNature", TypeName="int")]
    public uint ResNature { get; set; }

    [Column("resShadow", TypeName="int")]
    public uint ResShadow { get; set; }

    [Column("spirit", TypeName="int")]
    public uint Spirit { get; set; }

    [Column("stamina", TypeName="int")]
    public uint Stamina { get; set; }

    [Column("strength", TypeName="int")]
    public uint Strength { get; set; }

}
[Table("character_tutorial")]
public sealed class CharacterTutorial
{
    /* Account Identifier */
    [Column("account", TypeName="bigint")]
    public ulong Account { get; set; }

    [Column("tut0", TypeName="int")]
    public uint Tut0 { get; set; }

    [Column("tut1", TypeName="int")]
    public uint Tut1 { get; set; }

    [Column("tut2", TypeName="int")]
    public uint Tut2 { get; set; }

    [Column("tut3", TypeName="int")]
    public uint Tut3 { get; set; }

    [Column("tut4", TypeName="int")]
    public uint Tut4 { get; set; }

    [Column("tut5", TypeName="int")]
    public uint Tut5 { get; set; }

    [Column("tut6", TypeName="int")]
    public uint Tut6 { get; set; }

    [Column("tut7", TypeName="int")]
    public uint Tut7 { get; set; }

}
[Table("characters")]
public sealed class Characters
{
    /* Account Identifier */
    [Column("account", TypeName="int")]
    public uint Account { get; set; }

    [Column("actionBars", TypeName="tinyint")]
    public byte ActionBars { get; set; }

    [Column("ammoId", TypeName="int")]
    public uint AmmoId { get; set; }

    [Column("at_login", TypeName="int")]
    public uint AtLogin { get; set; }

    [Column("cinematic", TypeName="tinyint")]
    public byte Cinematic { get; set; }

    [Column("Class", TypeName="tinyint")]
    public byte Class { get; set; }

    [Column("death_expire_time", TypeName="bigint")]
    public ulong DeathExpireTime { get; set; }

    [Column("deleteDate", TypeName="bigint")]
    public ulong DeleteDate { get; set; }

    [Column("deleteInfos_Account", TypeName="int")]
    public uint DeleteInfosAccount { get; set; }

    [Column("deleteInfos_Name")]
    [MaxLength(12)]
    public string DeleteInfosName { get; set; }

    [Column("drunk", TypeName="smallint")]
    public ushort Drunk { get; set; }

    [Column("equipmentCache", TypeName="longtext")]
    public string EquipmentCache { get; set; }

    [Column("exploredZones", TypeName="longtext")]
    public string ExploredZones { get; set; }

    [Column("extra_flags", TypeName="int")]
    public uint ExtraFlags { get; set; }

    [Column("gender", TypeName="tinyint")]
    public byte Gender { get; set; }

    [Column("grantableLevels", TypeName="int")]
    public uint GrantableLevels { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("health", TypeName="int")]
    public uint Health { get; set; }

    [Column("honor_highest_rank", TypeName="int")]
    public uint HonorHighestRank { get; set; }

    [Column("honor_standing", TypeName="int")]
    public uint HonorStanding { get; set; }

    [Column("is_logout_resting", TypeName="tinyint")]
    public byte IsLogoutResting { get; set; }

    [Column("level", TypeName="tinyint")]
    public byte Level { get; set; }

    [Column("leveltime", TypeName="int")]
    public uint Leveltime { get; set; }

    [Column("logout_time", TypeName="bigint")]
    public ulong LogoutTime { get; set; }

    /* Map Identifier */
    [Column("map", TypeName="int")]
    public uint Map { get; set; }

    [Column("money", TypeName="int")]
    public uint Money { get; set; }

    [Column("name")]
    [MaxLength(12)]
    public string Name { get; set; }

    [Column("online", TypeName="tinyint")]
    public byte Online { get; set; }

    [Column("orientation", TypeName="float")]
    public float Orientation { get; set; }

    [Column("playerBytes", TypeName="int")]
    public uint PlayerBytes { get; set; }

    [Column("playerBytes2", TypeName="int")]
    public uint PlayerBytes2 { get; set; }

    [Column("playerFlags", TypeName="int")]
    public uint PlayerFlags { get; set; }

    [Column("position_x", TypeName="float")]
    public float PositionX { get; set; }

    [Column("position_y", TypeName="float")]
    public float PositionY { get; set; }

    [Column("position_z", TypeName="float")]
    public float PositionZ { get; set; }

    [Column("power1", TypeName="int")]
    public uint Power1 { get; set; }

    [Column("power2", TypeName="int")]
    public uint Power2 { get; set; }

    [Column("power3", TypeName="int")]
    public uint Power3 { get; set; }

    [Column("power4", TypeName="int")]
    public uint Power4 { get; set; }

    [Column("power5", TypeName="int")]
    public uint Power5 { get; set; }

    [Column("race", TypeName="tinyint")]
    public byte Race { get; set; }

    [Column("resettalents_cost", TypeName="int")]
    public uint ResettalentsCost { get; set; }

    [Column("resettalents_time", TypeName="bigint")]
    public ulong ResettalentsTime { get; set; }

    [Column("rest_bonus", TypeName="float")]
    public float RestBonus { get; set; }

    [Column("stable_slots", TypeName="tinyint")]
    public byte StableSlots { get; set; }

    [Column("stored_dishonorable_kills", TypeName="int")]
    public int StoredDishonorableKills { get; set; }

    [Column("stored_honor_rating", TypeName="float")]
    public float StoredHonorRating { get; set; }

    [Column("stored_honorable_kills", TypeName="int")]
    public int StoredHonorableKills { get; set; }

    [Column("taxi_path", TypeName="text")]
    [MaxLength(65535)]
    public string TaxiPath { get; set; }

    [Column("taximask", TypeName="longtext")]
    public string Taximask { get; set; }

    [Column("totaltime", TypeName="int")]
    public uint Totaltime { get; set; }

    [Column("trans_o", TypeName="float")]
    public float TransO { get; set; }

    [Column("trans_x", TypeName="float")]
    public float TransX { get; set; }

    [Column("trans_y", TypeName="float")]
    public float TransY { get; set; }

    [Column("trans_z", TypeName="float")]
    public float TransZ { get; set; }

    [Column("transguid", TypeName="bigint")]
    public ulong Transguid { get; set; }

    [Column("watchedFaction", TypeName="int")]
    public uint WatchedFaction { get; set; }

    [Column("xp", TypeName="int")]
    public uint Xp { get; set; }

    [Column("zone", TypeName="int")]
    public uint Zone { get; set; }

}
[Table("corpse")]
public sealed class Corpse
{
    [Column("corpse_type", TypeName="tinyint")]
    public byte CorpseType { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("instance", TypeName="int")]
    public uint Instance { get; set; }

    /* Map Identifier */
    [Column("map", TypeName="int")]
    public uint Map { get; set; }

    [Column("orientation", TypeName="float")]
    public float Orientation { get; set; }

    /* Character Global Unique Identifier */
    [Column("player", TypeName="int")]
    public uint Player { get; set; }

    [Column("position_x", TypeName="float")]
    public float PositionX { get; set; }

    [Column("position_y", TypeName="float")]
    public float PositionY { get; set; }

    [Column("position_z", TypeName="float")]
    public float PositionZ { get; set; }

    [Column("time", TypeName="bigint")]
    public ulong Time { get; set; }

}
[Table("creature_respawn")]
public sealed class CreatureRespawn
{
    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("instance", TypeName="mediumint")]
    public uint Instance { get; set; }

    [Column("respawntime", TypeName="bigint")]
    public ulong Respawntime { get; set; }

}
[Table("game_event_status")]
public sealed class GameEventStatus
{
    [Column("Event", TypeName="smallint")]
    public ushort Event { get; set; }

}
[Table("gameobject_respawn")]
public sealed class GameobjectRespawn
{
    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("instance", TypeName="mediumint")]
    public uint Instance { get; set; }

    [Column("respawntime", TypeName="bigint")]
    public ulong Respawntime { get; set; }

}
[Table("gm_surveys")]
public sealed class GmSurveys
{
    [Column("answer1", TypeName="tinyint")]
    public byte Answer1 { get; set; }

    [Column("answer10", TypeName="tinyint")]
    public byte Answer10 { get; set; }

    [Column("answer2", TypeName="tinyint")]
    public byte Answer2 { get; set; }

    [Column("answer3", TypeName="tinyint")]
    public byte Answer3 { get; set; }

    [Column("answer4", TypeName="tinyint")]
    public byte Answer4 { get; set; }

    [Column("answer5", TypeName="tinyint")]
    public byte Answer5 { get; set; }

    [Column("answer6", TypeName="tinyint")]
    public byte Answer6 { get; set; }

    [Column("answer7", TypeName="tinyint")]
    public byte Answer7 { get; set; }

    [Column("answer8", TypeName="tinyint")]
    public byte Answer8 { get; set; }

    [Column("answer9", TypeName="tinyint")]
    public byte Answer9 { get; set; }

    /* Player's feedback */
    [Column("comment", TypeName="text")]
    [MaxLength(65535)]
    public string Comment { get; set; }

    /* Survey DBC entry's identifier */
    [Column("surveyid", TypeName="int")]
    public uint Surveyid { get; set; }

    /* GM Ticket's unique identifier */
    [Column("ticketid", TypeName="int")]
    public uint Ticketid { get; set; }

}
[Table("gm_tickets")]
public sealed class GmTickets
{
    /* Timestamp: ticket's last time answered by a GM */
    [Column("answered", TypeName="bigint")]
    public ulong Answered { get; set; }

    /* Assignee's character's Global Unique Identifier */
    [Column("assignee_guid", TypeName="int")]
    public uint AssigneeGuid { get; set; }

    /* Assignee's character's name */
    [Column("assignee_name")]
    [MaxLength(12)]
    public string AssigneeName { get; set; }

    /* Player's character Global Unique Identifier */
    [Column("author_guid", TypeName="int")]
    public uint AuthorGuid { get; set; }

    /* Player's character name */
    [Column("author_name")]
    [MaxLength(12)]
    public string AuthorName { get; set; }

    /* GM Ticket Category DBC entry's identifier */
    [Column("category", TypeName="tinyint")]
    public byte Category { get; set; }

    /* Timestamp: ticket closed by a GM */
    [Column("closed", TypeName="bigint")]
    public ulong Closed { get; set; }

    /* Assignee's final conclusion on this ticket */
    [Column("conclusion")]
    [MaxLength(255)]
    public string Conclusion { get; set; }

    /* Timestamp: ticket created by a player */
    [Column("created", TypeName="bigint")]
    public ulong Created { get; set; }

    /* GM Ticket's unique identifier */
    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    /* Ticket's security level */
    [Column("level", TypeName="tinyint")]
    public byte Level { get; set; }

    /* Player's client locale name */
    [Column("locale")]
    [MaxLength(4)]
    public string Locale { get; set; }

    /* Character's map identifier on submission */
    [Column("mapid", TypeName="int")]
    public uint Mapid { get; set; }

    /* Additional notes for GMs */
    [Column("notes")]
    [MaxLength(10000)]
    public string Notes { get; set; }

    /* Character's orientation angle on submission */
    [Column("o", TypeName="float")]
    public float O { get; set; }

    /* Timestamp: ticket's last time opened by a GM */
    [Column("seen", TypeName="bigint")]
    public ulong Seen { get; set; }

    /* Ticket's current state */
    [Column("state", TypeName="tinyint")]
    public byte State { get; set; }

    /* Ticket's current status */
    [Column("status", TypeName="tinyint")]
    public byte Status { get; set; }

    /* Ticket's message */
    [Column("text", TypeName="text")]
    [MaxLength(65535)]
    public string Text { get; set; }

    /* Timestamp: ticket text's last update */
    [Column("updated", TypeName="bigint")]
    public ulong Updated { get; set; }

    /* Character's x coordinate on submission */
    [Column("x", TypeName="float")]
    public float X { get; set; }

    /* Character's y coordinate on submission */
    [Column("y", TypeName="float")]
    public float Y { get; set; }

    /* Character's z coordinate on submission */
    [Column("z", TypeName="float")]
    public float Z { get; set; }

}
[Table("group_instance")]
public sealed class GroupInstance
{
    [Column("instance", TypeName="int")]
    public uint Instance { get; set; }

    [Column("leaderGuid", TypeName="int")]
    public uint LeaderGuid { get; set; }

    [Column("permanent", TypeName="tinyint")]
    public byte Permanent { get; set; }

}
[Table("group_member")]
public sealed class GroupMember
{
    [Column("assistant", TypeName="tinyint")]
    public byte Assistant { get; set; }

    [Column("groupId", TypeName="int")]
    public uint GroupId { get; set; }

    [Column("memberGuid", TypeName="int")]
    public uint MemberGuid { get; set; }

    [Column("subgroup", TypeName="smallint")]
    public ushort Subgroup { get; set; }

}
[Table("groups")]
public sealed class Groups
{
    [Column("groupId", TypeName="int")]
    public uint GroupId { get; set; }

    [Column("icon1", TypeName="int")]
    public uint Icon1 { get; set; }

    [Column("icon2", TypeName="int")]
    public uint Icon2 { get; set; }

    [Column("icon3", TypeName="int")]
    public uint Icon3 { get; set; }

    [Column("icon4", TypeName="int")]
    public uint Icon4 { get; set; }

    [Column("icon5", TypeName="int")]
    public uint Icon5 { get; set; }

    [Column("icon6", TypeName="int")]
    public uint Icon6 { get; set; }

    [Column("icon7", TypeName="int")]
    public uint Icon7 { get; set; }

    [Column("icon8", TypeName="int")]
    public uint Icon8 { get; set; }

    [Column("isRaid", TypeName="tinyint")]
    public byte IsRaid { get; set; }

    [Column("leaderGuid", TypeName="int")]
    public uint LeaderGuid { get; set; }

    [Column("looterGuid", TypeName="int")]
    public uint LooterGuid { get; set; }

    [Column("lootMethod", TypeName="tinyint")]
    public byte LootMethod { get; set; }

    [Column("lootThreshold", TypeName="tinyint")]
    public byte LootThreshold { get; set; }

    [Column("mainAssistant", TypeName="int")]
    public uint MainAssistant { get; set; }

    [Column("mainTank", TypeName="int")]
    public uint MainTank { get; set; }

}
[Table("guild")]
public sealed class Guild
{
    [Column("BackgroundColor", TypeName="int")]
    public int BackgroundColor { get; set; }

    [Column("BorderColor", TypeName="int")]
    public int BorderColor { get; set; }

    [Column("BorderStyle", TypeName="int")]
    public int BorderStyle { get; set; }

    [Column("createdate", TypeName="bigint")]
    public ulong Createdate { get; set; }

    [Column("EmblemColor", TypeName="int")]
    public int EmblemColor { get; set; }

    [Column("EmblemStyle", TypeName="int")]
    public int EmblemStyle { get; set; }

    [Column("guildid", TypeName="int")]
    public uint Guildid { get; set; }

    [Column("info")]
    [MaxLength(500)]
    public string Info { get; set; }

    [Column("leaderguid", TypeName="int")]
    public uint Leaderguid { get; set; }

    [Column("motd")]
    [MaxLength(128)]
    public string Motd { get; set; }

    [Column("name")]
    [MaxLength(255)]
    public string Name { get; set; }

}
[Table("guild_eventlog")]
public sealed class GuildEventlog
{
    /* Event type */
    [Column("EventType", TypeName="tinyint")]
    public byte EventType { get; set; }

    /* Guild Identificator */
    [Column("guildid", TypeName="int")]
    public uint Guildid { get; set; }

    /* Log record identificator - auxiliary column */
    [Column("LogGuid", TypeName="int")]
    public uint LogGuid { get; set; }

    /* New rank(in case promotion/demotion) */
    [Column("NewRank", TypeName="tinyint")]
    public byte NewRank { get; set; }

    /* Player 1 */
    [Column("PlayerGuid1", TypeName="int")]
    public uint PlayerGuid1 { get; set; }

    /* Player 2 */
    [Column("PlayerGuid2", TypeName="int")]
    public uint PlayerGuid2 { get; set; }

    /* Event UNIX time */
    [Column("TimeStamp", TypeName="bigint")]
    public ulong TimeStamp { get; set; }

}
[Table("guild_member")]
public sealed class GuildMember
{
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("guildid", TypeName="int")]
    public uint Guildid { get; set; }

    [Column("offnote")]
    [MaxLength(31)]
    public string Offnote { get; set; }

    [Column("pnote")]
    [MaxLength(31)]
    public string Pnote { get; set; }

    [Column("rank", TypeName="tinyint")]
    public byte Rank { get; set; }

}
[Table("guild_rank")]
public sealed class GuildRank
{
    [Column("guildid", TypeName="int")]
    public uint Guildid { get; set; }

    [Column("rid", TypeName="int")]
    public uint Rid { get; set; }

    [Column("rights", TypeName="int")]
    public uint Rights { get; set; }

    [Column("rname")]
    [MaxLength(255)]
    public string Rname { get; set; }

}
[Table("instance")]
public sealed class Instance
{
    [Column("data", TypeName="longtext")]
    public string Data { get; set; }

    [Column("encountersMask", TypeName="int")]
    public uint EncountersMask { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("map", TypeName="int")]
    public uint Map { get; set; }

    [Column("resettime", TypeName="bigint")]
    public ulong Resettime { get; set; }

}
[Table("instance_reset")]
public sealed class InstanceReset
{
    [Column("mapid", TypeName="int")]
    public uint Mapid { get; set; }

    [Column("resettime", TypeName="bigint")]
    public ulong Resettime { get; set; }

}
[Table("item_instance")]
public sealed class ItemInstance
{
    [Column("charges", TypeName="text")]
    [MaxLength(65535)]
    public string Charges { get; set; }

    [Column("count", TypeName="int")]
    public uint Count { get; set; }

    [Column("creatorGuid", TypeName="int")]
    public uint CreatorGuid { get; set; }

    [Column("durability", TypeName="int")]
    public uint Durability { get; set; }

    [Column("duration", TypeName="int")]
    public uint Duration { get; set; }

    [Column("enchantments", TypeName="text")]
    [MaxLength(65535)]
    public string Enchantments { get; set; }

    [Column("flags", TypeName="int")]
    public uint Flags { get; set; }

    [Column("giftCreatorGuid", TypeName="int")]
    public uint GiftCreatorGuid { get; set; }

    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("itemEntry", TypeName="mediumint")]
    public uint ItemEntry { get; set; }

    [Column("itemTextId", TypeName="mediumint")]
    public uint ItemTextId { get; set; }

    [Column("owner_guid", TypeName="int")]
    public uint OwnerGuid { get; set; }

    [Column("randomPropertyId", TypeName="smallint")]
    public short RandomPropertyId { get; set; }

}
[Table("item_loot")]
public sealed class ItemLoot
{
    [Column("amount", TypeName="int")]
    public uint Amount { get; set; }

    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("itemid", TypeName="int")]
    public uint Itemid { get; set; }

    [Column("owner_guid", TypeName="int")]
    public uint OwnerGuid { get; set; }

    [Column("property", TypeName="int")]
    public int Property { get; set; }

}
[Table("item_text")]
public sealed class ItemText
{
    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("text", TypeName="longtext")]
    public string Text { get; set; }

}
[Table("mail")]
public sealed class Mail
{
    [Column("Checked", TypeName="tinyint")]
    public byte Checked { get; set; }

    [Column("cod", TypeName="int")]
    public uint Cod { get; set; }

    [Column("deliver_time", TypeName="bigint")]
    public ulong DeliverTime { get; set; }

    [Column("expire_time", TypeName="bigint")]
    public ulong ExpireTime { get; set; }

    [Column("has_items", TypeName="tinyint")]
    public byte HasItems { get; set; }

    /* Identifier */
    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("itemTextId", TypeName="int")]
    public uint ItemTextId { get; set; }

    [Column("mailTemplateId", TypeName="mediumint")]
    public uint MailTemplateId { get; set; }

    [Column("messageType", TypeName="tinyint")]
    public byte MessageType { get; set; }

    [Column("money", TypeName="int")]
    public uint Money { get; set; }

    /* Character Global Unique Identifier */
    [Column("receiver", TypeName="int")]
    public uint Receiver { get; set; }

    /* Character Global Unique Identifier */
    [Column("sender", TypeName="int")]
    public uint Sender { get; set; }

    [Column("stationery", TypeName="tinyint")]
    public sbyte Stationery { get; set; }

    [Column("subject", TypeName="longtext")]
    public string Subject { get; set; }

}
[Table("mail_items")]
public sealed class MailItems
{
    [Column("item_guid", TypeName="int")]
    public int ItemGuid { get; set; }

    [Column("item_template", TypeName="int")]
    public int ItemTemplate { get; set; }

    [Column("mail_id", TypeName="int")]
    public int MailId { get; set; }

    /* Character Global Unique Identifier */
    [Column("receiver", TypeName="int")]
    public uint Receiver { get; set; }

}
[Table("pet_aura")]
public sealed class PetAura
{
    [Column("basepoints0", TypeName="int")]
    public int Basepoints0 { get; set; }

    [Column("basepoints1", TypeName="int")]
    public int Basepoints1 { get; set; }

    [Column("basepoints2", TypeName="int")]
    public int Basepoints2 { get; set; }

    /* Full Global Unique Identifier */
    [Column("caster_guid", TypeName="bigint")]
    public ulong CasterGuid { get; set; }

    [Column("effIndexMask", TypeName="int")]
    public uint EffIndexMask { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("item_guid", TypeName="int")]
    public uint ItemGuid { get; set; }

    [Column("maxduration", TypeName="int")]
    public int Maxduration { get; set; }

    [Column("periodictime0", TypeName="int")]
    public uint Periodictime0 { get; set; }

    [Column("periodictime1", TypeName="int")]
    public uint Periodictime1 { get; set; }

    [Column("periodictime2", TypeName="int")]
    public uint Periodictime2 { get; set; }

    [Column("remaincharges", TypeName="int")]
    public uint Remaincharges { get; set; }

    [Column("remaintime", TypeName="int")]
    public int Remaintime { get; set; }

    [Column("spell", TypeName="int")]
    public uint Spell { get; set; }

    [Column("stackcount", TypeName="int")]
    public uint Stackcount { get; set; }

}
[Table("pet_spell")]
public sealed class PetSpell
{
    [Column("active", TypeName="int")]
    public uint Active { get; set; }

    /* Global Unique Identifier */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Spell Identifier */
    [Column("spell", TypeName="int")]
    public uint Spell { get; set; }

}
[Table("pet_spell_cooldown")]
public sealed class PetSpellCooldown
{
    /* Global Unique Identifier, Low part */
    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    /* Spell Identifier */
    [Column("spell", TypeName="int")]
    public uint Spell { get; set; }

    [Column("time", TypeName="bigint")]
    public ulong Time { get; set; }

}
[Table("petition")]
public sealed class Petition
{
    [Column("name")]
    [MaxLength(255)]
    public string Name { get; set; }

    [Column("ownerguid", TypeName="int")]
    public uint Ownerguid { get; set; }

    [Column("petitionguid", TypeName="int")]
    public uint Petitionguid { get; set; }

}
[Table("petition_sign")]
public sealed class PetitionSign
{
    [Column("ownerguid", TypeName="int")]
    public uint Ownerguid { get; set; }

    [Column("petitionguid", TypeName="int")]
    public uint Petitionguid { get; set; }

    [Column("player_account", TypeName="int")]
    public uint PlayerAccount { get; set; }

    [Column("playerguid", TypeName="int")]
    public uint Playerguid { get; set; }

}
[Table("playerbot_saved_data")]
public sealed class PlayerbotSavedData
{
    [Column("combat_delay", TypeName="int")]
    public uint CombatDelay { get; set; }

    [Column("combat_order", TypeName="tinyint")]
    public byte CombatOrder { get; set; }

    [Column("guid", TypeName="int")]
    public uint Guid { get; set; }

    [Column("pname")]
    [MaxLength(12)]
    public string Pname { get; set; }

    [Column("primary_target", TypeName="int")]
    public uint PrimaryTarget { get; set; }

    [Column("secondary_target", TypeName="int")]
    public uint SecondaryTarget { get; set; }

    [Column("sname")]
    [MaxLength(12)]
    public string Sname { get; set; }

}
[Table("pvpstats_battlegrounds")]
public sealed class PvpstatsBattlegrounds
{
    [Column("bracket_id", TypeName="tinyint")]
    public byte BracketId { get; set; }

    [Column("date", TypeName="datetime")]
    public DateTime Date { get; set; }

    [Column("id", TypeName="bigint")]
    public ulong Id { get; set; }

    [Column("type", TypeName="tinyint")]
    public byte Type { get; set; }

    [Column("winner_team", TypeName="tinyint")]
    public sbyte WinnerTeam { get; set; }

}
[Table("pvpstats_players")]
public sealed class PvpstatsPlayers
{
    [Column("attr_1", TypeName="mediumint")]
    public uint Attr1 { get; set; }

    [Column("attr_2", TypeName="mediumint")]
    public uint Attr2 { get; set; }

    [Column("attr_3", TypeName="mediumint")]
    public uint Attr3 { get; set; }

    [Column("attr_4", TypeName="mediumint")]
    public uint Attr4 { get; set; }

    [Column("attr_5", TypeName="mediumint")]
    public uint Attr5 { get; set; }

    [Column("battleground_id", TypeName="bigint")]
    public ulong BattlegroundId { get; set; }

    [Column("character_guid", TypeName="int")]
    public uint CharacterGuid { get; set; }

    [Column("score_bonus_honor", TypeName="mediumint")]
    public uint ScoreBonusHonor { get; set; }

    [Column("score_damage_done", TypeName="mediumint")]
    public uint ScoreDamageDone { get; set; }

    [Column("score_deaths", TypeName="mediumint")]
    public uint ScoreDeaths { get; set; }

    [Column("score_healing_done", TypeName="mediumint")]
    public uint ScoreHealingDone { get; set; }

    [Column("score_honorable_kills", TypeName="mediumint")]
    public uint ScoreHonorableKills { get; set; }

    [Column("score_killing_blows", TypeName="mediumint")]
    public uint ScoreKillingBlows { get; set; }

}
[Table("saved_variables")]
public sealed class SavedVariables
{
    [Column("cleaning_flags", TypeName="int")]
    public uint CleaningFlags { get; set; }

    [Column("NextMaintenanceDate", TypeName="int")]
    public uint NextMaintenanceDate { get; set; }

    [Column("NextWeeklyQuestResetTime", TypeName="bigint")]
    public ulong NextWeeklyQuestResetTime { get; set; }

}
[Table("world")]
public sealed class World
{
    [Column("data", TypeName="longtext")]
    public string Data { get; set; }

    [Column("map", TypeName="int")]
    public uint Map { get; set; }

}
[Table("world_state")]
public sealed class WorldState
{
    [Column("Data", TypeName="longtext")]
    public string Data { get; set; }

    /* Internal save ID */
    [Column("Id", TypeName="int")]
    public uint Id { get; set; }

}
