/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;

// ReSharper disable All

namespace MangosSharp.Data.Entities.CharacterDatabase;

public sealed class AccountInstancesEntered
{
    /* Player account */
    public uint AccountId { get; set; }

    /* Time when instance was entered */
    public long ExpireTime { get; set; }

    /* ID of instance entered */
    public uint InstanceId { get; set; }

}
public sealed class AhbotItems
{
    /* Chance item is added to AH upon bot visit, 0 for normal loot sources */
    public uint AddChance { get; set; }

    /* Item Identifier */
    public uint Item { get; set; }

    /* Max amount added, not used when add_chance is 0 */
    public uint MaxAmount { get; set; }

    /* Min amount added, not used when add_chance is 0 */
    public uint MinAmount { get; set; }

    /* Item value, a value of 0 bans item from being sold/bought by AHBot */
    public uint Value { get; set; }

}
public sealed class Auction
{
    public uint Buyguid { get; set; }

    public int Buyoutprice { get; set; }

    public int Deposit { get; set; }

    public uint Houseid { get; set; }

    public uint Id { get; set; }

    public uint ItemCount { get; set; }

    public int ItemRandompropertyid { get; set; }

    /* Item Identifier */
    public uint ItemTemplate { get; set; }

    public uint Itemguid { get; set; }

    public uint Itemowner { get; set; }

    public int Lastbid { get; set; }

    public int Startbid { get; set; }

    public ulong Time { get; set; }

}
public sealed class Bugreport
{
    public string Content { get; set; }

    /* Identifier */
    public int Id { get; set; }

    public string Type { get; set; }

}
public sealed class CharacterAction
{
    public uint Action { get; set; }

    public byte Button { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public byte Type { get; set; }

}
public sealed class CharacterAura
{
    public int Basepoints0 { get; set; }

    public int Basepoints1 { get; set; }

    public int Basepoints2 { get; set; }

    /* Full Global Unique Identifier */
    public ulong CasterGuid { get; set; }

    public uint EffIndexMask { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint ItemGuid { get; set; }

    public int Maxduration { get; set; }

    public uint Periodictime0 { get; set; }

    public uint Periodictime1 { get; set; }

    public uint Periodictime2 { get; set; }

    public uint Remaincharges { get; set; }

    public int Remaintime { get; set; }

    public uint Spell { get; set; }

    public uint Stackcount { get; set; }

}
public sealed class CharacterBattlegroundData
{
    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint InstanceId { get; set; }

    public int JoinMap { get; set; }

    public float JoinO { get; set; }

    public float JoinX { get; set; }

    public float JoinY { get; set; }

    public float JoinZ { get; set; }

    public uint Team { get; set; }

}
public sealed class CharacterGifts
{
    public uint Entry { get; set; }

    public uint Flags { get; set; }

    public uint Guid { get; set; }

    public uint ItemGuid { get; set; }

}
public sealed class CharacterHomebind
{
    /* Global Unique Identifier */
    public uint Guid { get; set; }

    /* Map Identifier */
    public uint Map { get; set; }

    public float PositionX { get; set; }

    public float PositionY { get; set; }

    public float PositionZ { get; set; }

    /* Zone Identifier */
    public uint Zone { get; set; }

}
public sealed class CharacterHonorCp
{
    public uint Date { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public float Honor { get; set; }

    public byte Type { get; set; }

    /* Creature / Player Identifier */
    public uint Victim { get; set; }

    public byte VictimType { get; set; }

}
public sealed class CharacterInstance
{
    public uint Guid { get; set; }

    public uint Instance { get; set; }

    public byte Permanent { get; set; }

}
public sealed class CharacterInventory
{
    public uint Bag { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    /* Item Global Unique Identifier */
    public uint Item { get; set; }

    /* Item Identifier */
    public uint ItemTemplate { get; set; }

    public byte Slot { get; set; }

}
public sealed class CharacterPet
{
    public string Abdata { get; set; }

    public uint CreatedBySpell { get; set; }

    public uint Curhappiness { get; set; }

    public uint Curhealth { get; set; }

    public uint Curmana { get; set; }

    public uint Entry { get; set; }

    public uint Exp { get; set; }

    public uint Id { get; set; }

    public uint Level { get; set; }

    public uint Loyalty { get; set; }

    public int Loyaltypoints { get; set; }

    public uint? Modelid { get; set; }

    public string Name { get; set; }

    public uint Owner { get; set; }

    public byte PetType { get; set; }

    public byte Reactstate { get; set; }

    public byte Renamed { get; set; }

    public uint ResettalentsCost { get; set; }

    public ulong ResettalentsTime { get; set; }

    public ulong Savetime { get; set; }

    public uint Slot { get; set; }

    public string Teachspelldata { get; set; }

    public int Trainpoint { get; set; }

    public uint XpForNextLoyalty { get; set; }

}
public sealed class CharacterQueststatus
{
    public byte Explored { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint Itemcount1 { get; set; }

    public uint Itemcount2 { get; set; }

    public uint Itemcount3 { get; set; }

    public uint Itemcount4 { get; set; }

    public uint Mobcount1 { get; set; }

    public uint Mobcount2 { get; set; }

    public uint Mobcount3 { get; set; }

    public uint Mobcount4 { get; set; }

    /* Quest Identifier */
    public uint Quest { get; set; }

    public byte Rewarded { get; set; }

    public uint Status { get; set; }

    public ulong Timer { get; set; }

}
public sealed class CharacterQueststatusWeekly
{
    /* Global Unique Identifier */
    public uint Guid { get; set; }

    /* Quest Identifier */
    public uint Quest { get; set; }

}
public sealed class CharacterReputation
{
    public uint Faction { get; set; }

    public int Flags { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public int Standing { get; set; }

}
public sealed class CharacterSkills
{
    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint Max { get; set; }

    public uint Skill { get; set; }

    public uint Value { get; set; }

}
public sealed class CharacterSocial
{
    /* Friend Flags */
    public byte Flags { get; set; }

    /* Friend Global Unique Identifier */
    public uint Friend { get; set; }

    /* Character Global Unique Identifier */
    public uint Guid { get; set; }

}
public sealed class CharacterSpell
{
    public byte Active { get; set; }

    public byte Disabled { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    /* Spell Identifier */
    public uint Spell { get; set; }

}
public sealed class CharacterSpellCooldown
{
    /* Spell category */
    public uint Category { get; set; }

    /* Spell category cooldown expire time */
    public ulong CategoryExpireTime { get; set; }

    /* Global Unique Identifier, Low part */
    public uint Guid { get; set; }

    /* Item Identifier */
    public uint ItemId { get; set; }

    /* Spell cooldown expire time */
    public ulong SpellExpireTime { get; set; }

    /* Spell Identifier */
    public uint SpellId { get; set; }

}
public sealed class CharacterStats
{
    public uint Agility { get; set; }

    public uint Armor { get; set; }

    public uint AttackPower { get; set; }

    public float BlockPct { get; set; }

    public float CritPct { get; set; }

    public float DodgePct { get; set; }

    /* Global Unique Identifier, Low part */
    public uint Guid { get; set; }

    public uint Intellect { get; set; }

    public uint Maxhealth { get; set; }

    public uint Maxpower1 { get; set; }

    public uint Maxpower2 { get; set; }

    public uint Maxpower3 { get; set; }

    public uint Maxpower4 { get; set; }

    public uint Maxpower5 { get; set; }

    public uint Maxpower6 { get; set; }

    public uint Maxpower7 { get; set; }

    public float ParryPct { get; set; }

    public uint RangedAttackPower { get; set; }

    public float RangedCritPct { get; set; }

    public uint ResArcane { get; set; }

    public uint ResFire { get; set; }

    public uint ResFrost { get; set; }

    public uint ResHoly { get; set; }

    public uint ResNature { get; set; }

    public uint ResShadow { get; set; }

    public uint Spirit { get; set; }

    public uint Stamina { get; set; }

    public uint Strength { get; set; }

}
public sealed class CharacterTutorial
{
    /* Account Identifier */
    public ulong Account { get; set; }

    public uint Tut0 { get; set; }

    public uint Tut1 { get; set; }

    public uint Tut2 { get; set; }

    public uint Tut3 { get; set; }

    public uint Tut4 { get; set; }

    public uint Tut5 { get; set; }

    public uint Tut6 { get; set; }

    public uint Tut7 { get; set; }

}
public sealed class Characters
{
    /* Account Identifier */
    public uint Account { get; set; }

    public byte ActionBars { get; set; }

    public uint AmmoId { get; set; }

    public uint AtLogin { get; set; }

    public byte Cinematic { get; set; }

    public byte Class { get; set; }

    public ulong DeathExpireTime { get; set; }

    public ulong? DeleteDate { get; set; }

    public uint? DeleteInfosAccount { get; set; }

    public string DeleteInfosName { get; set; }

    public ushort Drunk { get; set; }

    public string EquipmentCache { get; set; }

    public string ExploredZones { get; set; }

    public uint ExtraFlags { get; set; }

    public byte Gender { get; set; }

    public uint? GrantableLevels { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint Health { get; set; }

    public uint HonorHighestRank { get; set; }

    public uint HonorStanding { get; set; }

    public byte IsLogoutResting { get; set; }

    public byte Level { get; set; }

    public uint Leveltime { get; set; }

    public ulong LogoutTime { get; set; }

    /* Map Identifier */
    public uint Map { get; set; }

    public uint Money { get; set; }

    public string Name { get; set; }

    public byte Online { get; set; }

    public float Orientation { get; set; }

    public uint PlayerBytes { get; set; }

    public uint PlayerBytes2 { get; set; }

    public uint PlayerFlags { get; set; }

    public float PositionX { get; set; }

    public float PositionY { get; set; }

    public float PositionZ { get; set; }

    public uint Power1 { get; set; }

    public uint Power2 { get; set; }

    public uint Power3 { get; set; }

    public uint Power4 { get; set; }

    public uint Power5 { get; set; }

    public byte Race { get; set; }

    public uint ResettalentsCost { get; set; }

    public ulong ResettalentsTime { get; set; }

    public float RestBonus { get; set; }

    public byte StableSlots { get; set; }

    public int StoredDishonorableKills { get; set; }

    public float StoredHonorRating { get; set; }

    public int StoredHonorableKills { get; set; }

    public string TaxiPath { get; set; }

    public string Taximask { get; set; }

    public uint Totaltime { get; set; }

    public float TransO { get; set; }

    public float TransX { get; set; }

    public float TransY { get; set; }

    public float TransZ { get; set; }

    public ulong Transguid { get; set; }

    public uint WatchedFaction { get; set; }

    public uint Xp { get; set; }

    public uint Zone { get; set; }

}
public sealed class Corpse
{
    public byte CorpseType { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint Instance { get; set; }

    /* Map Identifier */
    public uint Map { get; set; }

    public float Orientation { get; set; }

    /* Character Global Unique Identifier */
    public uint Player { get; set; }

    public float PositionX { get; set; }

    public float PositionY { get; set; }

    public float PositionZ { get; set; }

    public ulong Time { get; set; }

}
public sealed class CreatureRespawn
{
    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint Instance { get; set; }

    public ulong Respawntime { get; set; }

}
public sealed class GameEventStatus
{
    public ushort Event { get; set; }

}
public sealed class GameobjectRespawn
{
    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint Instance { get; set; }

    public ulong Respawntime { get; set; }

}
public sealed class GmSurveys
{
    public byte? Answer1 { get; set; }

    public byte? Answer10 { get; set; }

    public byte? Answer2 { get; set; }

    public byte? Answer3 { get; set; }

    public byte? Answer4 { get; set; }

    public byte? Answer5 { get; set; }

    public byte? Answer6 { get; set; }

    public byte? Answer7 { get; set; }

    public byte? Answer8 { get; set; }

    public byte? Answer9 { get; set; }

    /* Player's feedback */
    public string Comment { get; set; }

    /* Survey DBC entry's identifier */
    public uint Surveyid { get; set; }

    /* GM Ticket's unique identifier */
    public uint Ticketid { get; set; }

}
public sealed class GmTickets
{
    /* Timestamp: ticket's last time answered by a GM */
    public ulong Answered { get; set; }

    /* Assignee's character's Global Unique Identifier */
    public uint AssigneeGuid { get; set; }

    /* Assignee's character's name */
    public string AssigneeName { get; set; }

    /* Player's character Global Unique Identifier */
    public uint AuthorGuid { get; set; }

    /* Player's character name */
    public string AuthorName { get; set; }

    /* GM Ticket Category DBC entry's identifier */
    public byte Category { get; set; }

    /* Timestamp: ticket closed by a GM */
    public ulong Closed { get; set; }

    /* Assignee's final conclusion on this ticket */
    public string Conclusion { get; set; }

    /* Timestamp: ticket created by a player */
    public ulong Created { get; set; }

    /* GM Ticket's unique identifier */
    public uint Id { get; set; }

    /* Ticket's security level */
    public byte Level { get; set; }

    /* Player's client locale name */
    public string Locale { get; set; }

    /* Character's map identifier on submission */
    public uint Mapid { get; set; }

    /* Additional notes for GMs */
    public string Notes { get; set; }

    /* Character's orientation angle on submission */
    public float O { get; set; }

    /* Timestamp: ticket's last time opened by a GM */
    public ulong Seen { get; set; }

    /* Ticket's current state */
    public byte State { get; set; }

    /* Ticket's current status */
    public byte Status { get; set; }

    /* Ticket's message */
    public string Text { get; set; }

    /* Timestamp: ticket text's last update */
    public ulong Updated { get; set; }

    /* Character's x coordinate on submission */
    public float X { get; set; }

    /* Character's y coordinate on submission */
    public float Y { get; set; }

    /* Character's z coordinate on submission */
    public float Z { get; set; }

}
public sealed class GroupInstance
{
    public uint Instance { get; set; }

    public uint LeaderGuid { get; set; }

    public byte Permanent { get; set; }

}
public sealed class GroupMember
{
    public byte Assistant { get; set; }

    public uint GroupId { get; set; }

    public uint MemberGuid { get; set; }

    public ushort Subgroup { get; set; }

}
public sealed class Groups
{
    public uint GroupId { get; set; }

    public uint Icon1 { get; set; }

    public uint Icon2 { get; set; }

    public uint Icon3 { get; set; }

    public uint Icon4 { get; set; }

    public uint Icon5 { get; set; }

    public uint Icon6 { get; set; }

    public uint Icon7 { get; set; }

    public uint Icon8 { get; set; }

    public byte IsRaid { get; set; }

    public uint LeaderGuid { get; set; }

    public uint LooterGuid { get; set; }

    public byte LootMethod { get; set; }

    public byte LootThreshold { get; set; }

    public uint MainAssistant { get; set; }

    public uint MainTank { get; set; }

}
public sealed class Guild
{
    public int BackgroundColor { get; set; }

    public int BorderColor { get; set; }

    public int BorderStyle { get; set; }

    public ulong Createdate { get; set; }

    public int EmblemColor { get; set; }

    public int EmblemStyle { get; set; }

    public uint Guildid { get; set; }

    public string Info { get; set; }

    public uint Leaderguid { get; set; }

    public string Motd { get; set; }

    public string Name { get; set; }

}
public sealed class GuildEventlog
{
    /* Event type */
    public byte EventType { get; set; }

    /* Guild Identificator */
    public uint Guildid { get; set; }

    /* Log record identificator - auxiliary column */
    public uint LogGuid { get; set; }

    /* New rank(in case promotion/demotion) */
    public byte NewRank { get; set; }

    /* Player 1 */
    public uint PlayerGuid1 { get; set; }

    /* Player 2 */
    public uint PlayerGuid2 { get; set; }

    /* Event UNIX time */
    public ulong TimeStamp { get; set; }

}
public sealed class GuildMember
{
    public uint Guid { get; set; }

    public uint Guildid { get; set; }

    public string Offnote { get; set; }

    public string Pnote { get; set; }

    public byte Rank { get; set; }

}
public sealed class GuildRank
{
    public uint Guildid { get; set; }

    public uint Rid { get; set; }

    public uint Rights { get; set; }

    public string Rname { get; set; }

}
public sealed class Instance
{
    public string Data { get; set; }

    public uint EncountersMask { get; set; }

    public uint Id { get; set; }

    public uint Map { get; set; }

    public ulong Resettime { get; set; }

}
public sealed class InstanceReset
{
    public uint Mapid { get; set; }

    public ulong Resettime { get; set; }

}
public sealed class ItemInstance
{
    public string Charges { get; set; }

    public uint Count { get; set; }

    public uint CreatorGuid { get; set; }

    public uint Durability { get; set; }

    public uint Duration { get; set; }

    public string Enchantments { get; set; }

    public uint Flags { get; set; }

    public uint GiftCreatorGuid { get; set; }

    public uint Guid { get; set; }

    public uint ItemEntry { get; set; }

    public uint ItemTextId { get; set; }

    public uint OwnerGuid { get; set; }

    public short RandomPropertyId { get; set; }

}
public sealed class ItemLoot
{
    public uint Amount { get; set; }

    public uint Guid { get; set; }

    public uint Itemid { get; set; }

    public uint OwnerGuid { get; set; }

    public int Property { get; set; }

}
public sealed class ItemText
{
    public uint Id { get; set; }

    public string Text { get; set; }

}
public sealed class Mail
{
    public byte Checked { get; set; }

    public uint Cod { get; set; }

    public ulong DeliverTime { get; set; }

    public ulong ExpireTime { get; set; }

    public byte HasItems { get; set; }

    /* Identifier */
    public uint Id { get; set; }

    public uint ItemTextId { get; set; }

    public uint MailTemplateId { get; set; }

    public byte MessageType { get; set; }

    public uint Money { get; set; }

    /* Character Global Unique Identifier */
    public uint Receiver { get; set; }

    /* Character Global Unique Identifier */
    public uint Sender { get; set; }

    public byte Stationery { get; set; }

    public string Subject { get; set; }

}
public sealed class MailItems
{
    public int ItemGuid { get; set; }

    public int ItemTemplate { get; set; }

    public int MailId { get; set; }

    /* Character Global Unique Identifier */
    public uint Receiver { get; set; }

}
public sealed class PetAura
{
    public int Basepoints0 { get; set; }

    public int Basepoints1 { get; set; }

    public int Basepoints2 { get; set; }

    /* Full Global Unique Identifier */
    public ulong CasterGuid { get; set; }

    public uint EffIndexMask { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    public uint ItemGuid { get; set; }

    public int Maxduration { get; set; }

    public uint Periodictime0 { get; set; }

    public uint Periodictime1 { get; set; }

    public uint Periodictime2 { get; set; }

    public uint Remaincharges { get; set; }

    public int Remaintime { get; set; }

    public uint Spell { get; set; }

    public uint Stackcount { get; set; }

}
public sealed class PetSpell
{
    public uint Active { get; set; }

    /* Global Unique Identifier */
    public uint Guid { get; set; }

    /* Spell Identifier */
    public uint Spell { get; set; }

}
public sealed class PetSpellCooldown
{
    /* Global Unique Identifier, Low part */
    public uint Guid { get; set; }

    /* Spell Identifier */
    public uint Spell { get; set; }

    public ulong Time { get; set; }

}
public sealed class Petition
{
    public string Name { get; set; }

    public uint Ownerguid { get; set; }

    public uint? Petitionguid { get; set; }

}
public sealed class PetitionSign
{
    public uint Ownerguid { get; set; }

    public uint Petitionguid { get; set; }

    public uint PlayerAccount { get; set; }

    public uint Playerguid { get; set; }

}
public sealed class PlayerbotSavedData
{
    public uint CombatDelay { get; set; }

    public byte CombatOrder { get; set; }

    public uint Guid { get; set; }

    public string Pname { get; set; }

    public uint PrimaryTarget { get; set; }

    public uint SecondaryTarget { get; set; }

    public string Sname { get; set; }

}
public sealed class PvpstatsBattlegrounds
{
    public byte BracketId { get; set; }

    public DateTime Date { get; set; }

    public ulong Id { get; set; }

    public byte Type { get; set; }

    public byte WinnerTeam { get; set; }

}
public sealed class PvpstatsPlayers
{
    public uint Attr1 { get; set; }

    public uint Attr2 { get; set; }

    public uint Attr3 { get; set; }

    public uint Attr4 { get; set; }

    public uint Attr5 { get; set; }

    public ulong BattlegroundId { get; set; }

    public uint CharacterGuid { get; set; }

    public uint ScoreBonusHonor { get; set; }

    public uint ScoreDamageDone { get; set; }

    public uint ScoreDeaths { get; set; }

    public uint ScoreHealingDone { get; set; }

    public uint ScoreHonorableKills { get; set; }

    public uint ScoreKillingBlows { get; set; }

}
public sealed class SavedVariables
{
    public uint CleaningFlags { get; set; }

    public uint NextMaintenanceDate { get; set; }

    public ulong NextWeeklyQuestResetTime { get; set; }

}
public sealed class World
{
    public string Data { get; set; }

    public uint Map { get; set; }

}
public sealed class WorldState
{
    public string Data { get; set; }

    /* Internal save ID */
    public uint Id { get; set; }

}
