/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// ReSharper disable All

namespace Mangos.Data.Entities.RealmDatabase;

[Table("account")]
public class Account
{
    [Column("active_realm_id", TypeName="int")]
    public virtual uint ActiveRealmId { get; set; }

    [Column("email", TypeName="text")]
    [MaxLength(65535)]
    public virtual string Email { get; set; }

    [Column("expansion", TypeName="tinyint")]
    public virtual byte Expansion { get; set; }

    [Column("failed_logins", TypeName="int")]
    public virtual uint FailedLogins { get; set; }

    [Column("flags", TypeName="int")]
    public virtual uint Flags { get; set; }

    [Column("gmlevel", TypeName="tinyint")]
    public virtual byte Gmlevel { get; set; }

    /* Identifier */
    [Column("id", TypeName="int")]
    public virtual uint Id { get; set; }

    [Column("joindate", TypeName="timestamp")]
    public virtual DateTimeOffset Joindate { get; set; }

    [Column("last_module", TypeName="char")]
    [MaxLength(32)]
    public virtual string LastModule { get; set; }

    [Column("locale")]
    [MaxLength(4)]
    public virtual string Locale { get; set; }

    [Column("locked", TypeName="tinyint")]
    public virtual byte Locked { get; set; }

    [Column("lockedIp")]
    [MaxLength(30)]
    public virtual string LockedIp { get; set; }

    [Column("module_day", TypeName="mediumint")]
    public virtual uint ModuleDay { get; set; }

    [Column("mutetime", TypeName="bigint")]
    public virtual ulong Mutetime { get; set; }

    [Column("os")]
    [MaxLength(4)]
    public virtual string Os { get; set; }

    [Column("s", TypeName="longtext")]
    public virtual string S { get; set; }

    [Column("sessionkey", TypeName="longtext")]
    public virtual string Sessionkey { get; set; }

    [Column("token", TypeName="text")]
    [MaxLength(65535)]
    public virtual string Token { get; set; }

    [Column("username")]
    [MaxLength(32)]
    public virtual string Username { get; set; }

    [Column("v", TypeName="longtext")]
    public virtual string V { get; set; }

}
[Table("account_banned")]
public class AccountBanned
{
    /* Account id */
    [Column("account_id", TypeName="int")]
    public virtual int AccountId { get; set; }

    [Column("active", TypeName="tinyint")]
    public virtual sbyte Active { get; set; }

    [Column("banned_at", TypeName="bigint")]
    public virtual long BannedAt { get; set; }

    [Column("banned_by")]
    [MaxLength(50)]
    public virtual string BannedBy { get; set; }

    [Column("expires_at", TypeName="bigint")]
    public virtual long ExpiresAt { get; set; }

    [Column("id", TypeName="int")]
    public virtual int Id { get; set; }

    [Column("reason")]
    [MaxLength(255)]
    public virtual string Reason { get; set; }

    [Column("unbanned_at", TypeName="bigint")]
    public virtual long UnbannedAt { get; set; }

    [Column("unbanned_by")]
    [MaxLength(50)]
    public virtual string UnbannedBy { get; set; }

}
[Table("account_logons")]
public class AccountLogons
{
    [Column("accountId", TypeName="int")]
    public virtual uint AccountId { get; set; }

    [Column("id", TypeName="int")]
    public virtual int Id { get; set; }

    [Column("ip")]
    [MaxLength(30)]
    public virtual string Ip { get; set; }

    [Column("loginSource", TypeName="int")]
    public virtual uint LoginSource { get; set; }

    [Column("loginTime", TypeName="timestamp")]
    public virtual DateTimeOffset LoginTime { get; set; }

}
[Table("account_raf")]
public class AccountRaf
{
    [Column("referred", TypeName="int")]
    public virtual uint Referred { get; set; }

    [Column("referrer", TypeName="int")]
    public virtual uint Referrer { get; set; }

}
[Table("antispam_blacklist")]
public class AntispamBlacklist
{
    [Column("string")]
    [MaxLength(64)]
    public virtual string String { get; set; }

}
[Table("antispam_replacement")]
public class AntispamReplacement
{
    [Column("from")]
    [MaxLength(32)]
    public virtual string From { get; set; }

    [Column("to")]
    [MaxLength(32)]
    public virtual string To { get; set; }

}
[Table("antispam_unicode_replacement")]
public class AntispamUnicodeReplacement
{
    [Column("from", TypeName="mediumint")]
    public virtual uint From { get; set; }

    [Column("to", TypeName="mediumint")]
    public virtual uint To { get; set; }

}
[Table("ip_banned")]
public class IpBanned
{
    [Column("banned_at", TypeName="bigint")]
    public virtual long BannedAt { get; set; }

    [Column("banned_by")]
    [MaxLength(50)]
    public virtual string BannedBy { get; set; }

    [Column("expires_at", TypeName="bigint")]
    public virtual long ExpiresAt { get; set; }

    [Column("ip")]
    [MaxLength(32)]
    public virtual string Ip { get; set; }

    [Column("reason")]
    [MaxLength(255)]
    public virtual string Reason { get; set; }

}
[Table("realmcharacters")]
public class Realmcharacters
{
    [Column("acctid", TypeName="bigint")]
    public virtual ulong Acctid { get; set; }

    [Column("numchars", TypeName="tinyint")]
    public virtual byte Numchars { get; set; }

    [Column("realmid", TypeName="int")]
    public virtual uint Realmid { get; set; }

}
[Table("realmlist")]
public class Realmlist
{
    [Column("address")]
    [MaxLength(32)]
    public virtual string Address { get; set; }

    [Column("allowedSecurityLevel", TypeName="tinyint")]
    public virtual byte AllowedSecurityLevel { get; set; }

    [Column("icon", TypeName="tinyint")]
    public virtual byte Icon { get; set; }

    [Column("id", TypeName="int")]
    public virtual uint Id { get; set; }

    [Column("name")]
    [MaxLength(32)]
    public virtual string Name { get; set; }

    [Column("population", TypeName="float")]
    public virtual float Population { get; set; }

    [Column("port", TypeName="int")]
    public virtual int Port { get; set; }

    [Column("realmbuilds")]
    [MaxLength(64)]
    public virtual string Realmbuilds { get; set; }

    /* Supported masks: 0x1 (invalid, not show in realm list), 0x2 (offline, set by mangosd), 0x4 (show version and build), 0x20 (new players), 0x40 (recommended) */
    [Column("realmflags", TypeName="tinyint")]
    public virtual byte Realmflags { get; set; }

    [Column("timezone", TypeName="tinyint")]
    public virtual byte Timezone { get; set; }

}
[Table("system_fingerprint_usage")]
public class SystemFingerprintUsage
{
    [Column("account", TypeName="int")]
    public virtual uint Account { get; set; }

    [Column("activecpus", TypeName="int")]
    public virtual uint Activecpus { get; set; }

    [Column("architecture")]
    [MaxLength(16)]
    public virtual string Architecture { get; set; }

    [Column("cputype")]
    [MaxLength(64)]
    public virtual string Cputype { get; set; }

    [Column("fingerprint", TypeName="int")]
    public virtual uint Fingerprint { get; set; }

    [Column("id", TypeName="int")]
    public virtual uint Id { get; set; }

    [Column("ip")]
    [MaxLength(16)]
    public virtual string Ip { get; set; }

    [Column("pagesize", TypeName="int")]
    public virtual uint Pagesize { get; set; }

    [Column("realm", TypeName="int")]
    public virtual uint Realm { get; set; }

    [Column("time", TypeName="datetime")]
    public virtual DateTimeOffset Time { get; set; }

    [Column("totalcpus", TypeName="int")]
    public virtual uint Totalcpus { get; set; }

}
[Table("uptime")]
public class Uptime
{
    [Column("maxplayers", TypeName="smallint")]
    public virtual ushort Maxplayers { get; set; }

    [Column("realmid", TypeName="int")]
    public virtual uint Realmid { get; set; }

    [Column("startstring")]
    [MaxLength(64)]
    public virtual string Startstring { get; set; }

    [Column("starttime", TypeName="bigint")]
    public virtual ulong Starttime { get; set; }

    [Column("uptime", TypeName="bigint")]
    public virtual ulong UpTime { get; set; }

}
