/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;

// ReSharper disable All

namespace MangosSharp.Data.Entities.LogsDatabase;

public sealed class LogsAnticheat
{
    public uint Account { get; set; }

    public uint? ActionMask { get; set; }

    public uint Fingerprint { get; set; }

    public uint Id { get; set; }

    public string Info { get; set; }

    public string Ip { get; set; }

    public string Player { get; set; }

    public uint Realm { get; set; }

    public DateTime? Time { get; set; }

}
public sealed class LogsSpamdetect
{
    public int? AccountId { get; set; }

    public string Comment { get; set; }

    public uint FromFingerprint { get; set; }

    public ulong? FromGuid { get; set; }

    public string FromIP { get; set; }

    public uint Id { get; set; }

    public uint Realm { get; set; }

    public DateTimeOffset Time { get; set; }

}
