/* THIS FILE IS AUTOMATICALLY GENERATED */

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// ReSharper disable All

namespace MangosSharp.Data.Entities.LogsDatabase;

[Table("logs_anticheat")]
public sealed class LogsAnticheat
{
    [Column("account", TypeName="int")]
    public uint Account { get; set; }

    [Column("actionMask", TypeName="int")]
    public uint? ActionMask { get; set; }

    [Column("fingerprint", TypeName="int")]
    public uint Fingerprint { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("info")]
    [MaxLength(512)]
    public string Info { get; set; }

    [Column("ip")]
    [MaxLength(16)]
    public string Ip { get; set; }

    [Column("player")]
    [MaxLength(32)]
    public string Player { get; set; }

    [Column("realm", TypeName="int")]
    public uint Realm { get; set; }

    [Column("time", TypeName="datetime")]
    public DateTime? Time { get; set; }

}
[Table("logs_spamdetect")]
public sealed class LogsSpamdetect
{
    [Column("accountId", TypeName="int")]
    public int? AccountId { get; set; }

    [Column("comment")]
    [MaxLength(8192)]
    public string Comment { get; set; }

    [Column("fromFingerprint", TypeName="int")]
    public uint FromFingerprint { get; set; }

    [Column("fromGuid", TypeName="bigint")]
    public ulong? FromGuid { get; set; }

    [Column("fromIP")]
    [MaxLength(16)]
    public string FromIP { get; set; }

    [Column("id", TypeName="int")]
    public uint Id { get; set; }

    [Column("realm", TypeName="int")]
    public uint Realm { get; set; }

    [Column("time", TypeName="timestamp")]
    public DateTimeOffset Time { get; set; }

}
